### PR TITLE
DO NOT MERGE YET: Remove init

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Do you continue to use the content of the MANIFEST to configure the DC if it doesn't yet exist ? @metacosm

**Comment by metacosm** [comment]
@cmoulliard yes, see https://github.com/snowdrop/spring-boot-cloud-devex/pull/69/files#diff-ff7686b39bf90dc2520886fb874371a4R175

**Comment by cmoulliard** [comment]
As the by default commands are still [there](https://goo.gl/KjW6CT), we can merge it. LGTM @metacosm

**Comment by metacosm** [comment]
Closes #68

**Pull request merged**
